name: Scan CVEs dispatch

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 1 * * *"

jobs:
  run-scan:
    name: Run scan for released images
    uses: alesancor1/template-test/.github/workflows/CVEscan-reusable.yaml@main
    with:
      oci-image-name: ghcr.io/alesancor1/template-test:0.1-24.04_edge
      create-issue: true
    secrets: inherit