name: Build and Publish Rocks to GHCR

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 1 * * *"

jobs:
  # prepare-matrix:
  #   runs-on: ubuntu-latest
  #   name: Prepare released image revisions to be tested
  #   outputs:
  #     released-revisions-matrix: ${{ steps.prepare-test-matrix.outputs.released-revisions-matrix }}
  #     last-scan: ${{ steps.last-scan.outputs.date }}
  #   steps:
  #     # TODO get an array of released images, the last-scan date and the oci directory
  #     - name: placeholder
  #       run: echo ""

  run-scan:
    name: Run scan for released images
    # needs: [prepare-test-matrix]
    # strategy:
      # fail-fast: false
      # matrix: ${{ fromJSON(needs.prepare-test-matrix.outputs.released-revisions-matrix) }}
    uses: ./.github/workflows/CVEscan-reusable.yaml #canonical/oci-factory/.github/workflows/Vulnerability-Scan.yaml@main
    with:
      oci-image-name: ghcr.io/alesancor1/template-test:0.1-24.04_edge # "${{ matrix.source-image }}"
      create-issue: true
    secrets: inherit