name: Rock pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  rock:
    uses: canonical/rocks-actions/.github/workflows/Rock.yaml@fix/skip-when-not-found
    secrets: inherit
    permissions:
      packages: write
