name: Threat monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  security:
    uses: canonical/rocks-actions/.github/workflows/Security.yaml@fix/skip-when-not-found
    secrets: inherit
    permissions:
      contents: read
      packages: read
